version: '3'
services:

  # mysql-5.5
  #mysql5.5:
  #  image: "mysql:5.5"
  #  container_name: "typeorm-mysql-5.5"
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: "admin"
  #    MYSQL_USER: "test"
  #    MYSQL_PASSWORD: "test"
  #    MYSQL_DATABASE: "test"

  # mysql
  mysql:
    image: "mysql:5.7.24"
    container_name: "typeorm-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # mariadb
  mariadb:
    image: "mariadb:10.1.37"
    container_name: "typeorm-mariadb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # postgres
  postgres:
    # mdillon/postgis is postgres + PostGIS (only). if you need additional
    # extensions, it's probably time to create a purpose-built image with all
    # necessary extensions. sorry, and thanks for adding support for them!
    image: "mdillon/postgis:9.6"
    container_name: "typeorm-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-GA-ubuntu"
    container_name: "typeorm-mssql"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"

  # cockroachdb
  cockroachdb:
    image: "cockroachdb/cockroach-unstable:v19.1.0-rc.2"
    container_name: "typeorm-cockroachdb"
    command: start --insecure
    ports:
      - "26257:26257"

  # mongodb
  mongodb:
    image: "mongo:3.4.18"
    container_name: "typeorm-mongodb"
    ports:
      - "27017:27017"

  # redis
  # redis:
  #   image: "redis:3.0.3"
  #   container_name: "typeorm-redis"
  #   ports:
  #     - "6379:6379"
